easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    condition: request.getHost() matches '/sto.automagistre.(ru|local)/'

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
