# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.extension.easy_admin:
        class: App\Twig\Extension\AppExtension
        arguments:
            - '@easyadmin.config.manager'
            - '@router'
            - '@request_stack'
            - '@property_accessor'
        tags:
            - { name: twig.extension }

    guzzle.middleware.ixora_auth:
        class: Closure
        factory: ['App\Guzzle\IxoraMiddleware', authQuery]
        arguments:
            - '%ixora_auth_code%'
        tags:
            - { name: csa_guzzle.middleware, alias: ixora_auth }

    guzzle.middleware.ixora_logger:
        class: Closure
        factory: ['App\Guzzle\IxoraMiddleware', logErrors]
        arguments:
            - '@logger'
        tags:
            - { name: csa_guzzle.middleware, alias: ixora_logger }

    app.part.finder:
        class: App\Part\Finder
        arguments:
            - '@csa_guzzle.client.ixora_ws'

    app.part.populator:
        class: App\Part\Populator
        arguments:
            - '@app.part.finder'
            - '@doctrine.orm.entity_manager'
