# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.extension.easy_admin:
        class: AppBundle\Twig\Extension\AppExtension
        arguments:
            - '@easyadmin.config.manager'
            - '@router'
            - '@request_stack'
            - '@property_accessor'
        tags:
            - { name: twig.extension }
