easy_admin:
    site_name: 'СТО Автомагистр'
    disabled_actions: ['delete']
    design:
        color_scheme: 'light'
    formats:
        date: 'd.m.Y'
        time: 'H:i'
        datetime: 'd.m.Y H:i'
#    form:

    list:
        max_results: 20
        actions:
            - { name: 'new', icon: 'plus', label: 'Создать' }
            - { name: 'show', icon: 'search', label: false }
            - { name: 'edit', icon: 'pencil', label: false }
            - { name: 'delete', icon: 'trash', label: false }
