easy_admin:
    entities:
        Order:
            class: AppBundle\Entity\Order
            controller: AppBundle\Controller\Admin\OrderController
            disabled_actions: ['new', 'edit', 'delete']
            templates:
                list: 'easy_admin/order/list.html.twig'
                show: 'easy_admin/order/show.html.twig'
            label: 'Заказ'
            list:
                title: 'Заказы'
                fields:
                    - { property: 'id', label: 'Номер', template: 'easy_admin/order/field_id.html.twig' }
                    - { property: 'status', label: 'Статус', template: 'easy_admin/order/field_status.html.twig' }
                    - { property: 'startedAt', label: 'Дата начала', type: 'datetime' }
                    - { property: 'closedAt', label: 'Дата закрытия', type: 'datetime' }
                    - { property: 'car', label: 'Автомобиль', template: 'easy_admin/order/field_car.html.twig' }
                    - { property: 'client', label: 'Клиент' }
                    - { property: 'readableCosts', label: 'Работы/Запчасти' }
        OrderOrganization:
            class: AppBundle\Entity\OrderOrganization
            controller: AppBundle\Controller\Admin\OrderController
            disabled_actions: ['show', 'edit', 'delete']
            templates:
                show: 'easy_admin/order/show.html.twig'
            form:
                fields:
                    - { type: 'group', label: 'Основная информация', css_class: 'col-sm-6' }
                    - { property: 'customer', label: 'Организация', type: 'easyadmin_autocomplete' }
                    - { property: 'car', label: 'Автомобиль', type: 'easyadmin_autocomplete' }
                    - { property: 'mileage', label: 'Пробег' }

                    - { type: 'group', label: 'Описание', css_class: 'col-sm-6' }
                    - { property: 'description', label: 'Описание', type: 'ckeditor' }
            new:
                title: 'Создать заказ'
        OrderPerson:
            class: AppBundle\Entity\OrderPerson
            controller: AppBundle\Controller\Admin\OrderController
            disabled_actions: ['show', 'edit', 'delete']
            templates:
                show: 'easy_admin/order/show.html.twig'
            form:
                fields:
                    - { type: 'group', label: 'Основная информация', css_class: 'col-sm-6' }
                    - { property: 'customer', label: 'Клиент', type: 'easyadmin_autocomplete' }
                    - { property: 'car', label: 'Автомобиль', type: 'easyadmin_autocomplete' }
                    - { property: 'mileage', label: 'Пробег' }

                    - { type: 'group', label: 'Описание', css_class: 'col-sm-6' }
                    - { property: 'description', label: 'Описание', type: 'ckeditor' }
            new:
                title: 'Создать заказ'

        OrderService:
            class: AppBundle\Entity\OrderService
            controller: AppBundle\Controller\Admin\OrderServiceController
            disabled_actions: ['show']
            edit:
                actions: ['delete']
            form:
                fields:
                    - { property: 'order', label: 'Заказ', type: 'text', type_options: { disabled: true } }
                    - { property: 'service', label: 'Работа', type: 'easyadmin_autocomplete' }
                    - { property: 'cost', label: 'Стоимость' }
                    - { property: 'user', label: 'Исполнитель', type: 'easyadmin_autocomplete' }
        OrderPart:
            class: AppBundle\Entity\OrderPart
            controller: AppBundle\Controller\Admin\OrderPartController
            disabled_actions: ['show']
            edit:
                actions: ['delete']
            form:
                fields:
                    - { property: 'order', label: 'Заказ', type: 'text', type_options: { disabled: true } }
                    - { property: 'orderService', label: 'Работа', type: 'text', type_options: { disabled: true } }
                    - { property: 'part', label: 'Запчасть', type: 'easyadmin_autocomplete' }
                    - { property: 'cost', label: 'Стоимость' }
                    - { property: 'quantity', label: 'Количество' }
        User:
            class: AppBundle\Entity\User

        Jobs:
            class: AppBundle\Entity\JobAdvice
        Service:
            class: AppBundle\Entity\Service
            controller: AppBundle\Controller\Admin\ServiceController

        Client:
            class: AppBundle\Entity\Client
            controller: AppBundle\Controller\Admin\ClientController
            disabled_actions: ['delete']
            list:
                title: 'Пользователи'
                fields:
                    - { property: 'person', label: 'Клиент', template: 'easy_admin/client/field_person.html.twig' }
                    - { property: 'person.telephone', label: 'Телефон', type: 'tel' }
                    - { property: 'person.email', label: 'Email', type: 'email' }
                    - { property: 'wallet', label: 'Баланс' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'employee', label: 'Сотрудник?', type: 'boolean' }
            form:
                fields:
                    - { property: 'person', label: 'Клиент' }
                    - { property: 'wallet', label: 'Баланс' }
                    - { property: 'description', label: 'Описание', type: 'ckeditor' }
                    - { property: 'employee', label: 'Сотрудник?' }
        Person:
            class: AppBundle\Entity\Person
            search:
                fields: ['firstname', 'lastname']
            list:
                fields:
                    - { property: 'fullName', label: 'Ф.И.О' }
                    - { property: 'telephone', label: 'Телефон', type: 'tel' }
            form:
                fields:
                    - { property: 'firstname', label: 'Имя' }
                    - { property: 'lastname', label: 'Фамилия' }
                    - { property: 'telephone', label: 'Телефон' }
        Organization:
            class: AppBundle\Entity\Organization
            disabled_actions: ['show', 'delete']

        Car:
            class: AppBundle\Entity\Car
            controller: AppBundle\Controller\Admin\CarController
            disabled_actions: ['delete']
            label: 'Автомобили'
            search:
                fields: ['gosnomer', 'vin']
            list:
                title: 'Автомобили'
                fields:
                    - { property: 'client', label: 'Владелец' }
                    - { property: 'carModificationDisplayName', label: 'Комплектация' }
                    - { property: 'year', label: 'Год', type: 'string' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'mileage', label: 'Пробег' }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false, template: 'easy_admin/car/field_gosnomer_img.html.twig' }
            show:
                fields:
                    - { property: 'client', label: 'Владелец' }
                    - { property: 'vin', label: 'VIN' }
                    - { property: 'carModificationDisplayName', label: 'Комплектация' }
                    - { property: 'year', label: 'Год', type: 'string' }
                    - { property: 'mileage', label: 'Пробег' }
                    - { property: 'gosnomer', label: 'Гос. Номер' }
            form:
                fields:
                    -
                        property: 'client'
                        label: 'Владелец'
                        type: 'easyadmin_autocomplete'
                        help: 'Фамилия, Имя, Телефон, E-mail'
                    - { property: 'carModel', label: 'Модель', type_options: { disabled: true } }
                    - { property: 'vin', label: 'VIN' }
                    -
                        property: 'carModification'
                        label: 'Модель'
                        type: 'easyadmin_autocomplete'
                        help: 'Проивзодитель, Модель, Поколение, Комплектация, Лошадинные силы'
                    - { property: 'gosnomer', label: 'Гос. Номер' }
                    - { property: 'description', label: 'Описание', type: 'ckeditor' }
            edit:
                fields:
                    - { property: 'vin', label: 'VIN', type_options: { disabled: true }  }

        Part:
            class: AppBundle\Entity\Part
            controller: AppBundle\Controller\Admin\PartController
            label: 'Запчасти'
            list:
                fields:
                    - { property: 'manufacturer.name', label: 'Производитель' }
                    - { property: 'partname', label: 'Название' }
                    - { property: 'partnumber', label: 'Номер' }
                    - { property: 'price', label: 'Цена' }
            form:
                fields:
                    - { property: 'manufacturer', label: 'Производитель' }
                    - { property: 'partname', label: 'Название' }
                    - { property: 'partnumber', label: 'Номер' }
                    - { property: 'price', label: 'Цена' }
            edit:
                fields: ['-price']
        Motion:
            class: AppBundle\Entity\Motion
            disabled_actions: ['show', 'edit', 'new', 'search']


        Manufacturer:
            class: AppBundle\Entity\Manufacturer
            disabled_actions: ['show']
            label: 'Производитель'
            search:
                fields: ['name']
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'logo', label: 'Logo' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'logo', label: 'Logo' }

        Model:
            class: AppBundle\Entity\CarModel
            controller: AppBundle\Controller\Admin\CarModelController
            disabled_actions: ['show']
            label: 'Модель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'manufacturer', label: 'Производитель' }
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'manufacturer', label: 'Производитель', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Название' }
            edit:
                fields:
                    - { property: 'manufacturer', label: 'Производитель', type_options: { disabled: true } }

        Generation:
            class: AppBundle\Entity\CarGeneration
            controller: AppBundle\Controller\Admin\CarGenerationController
            disabled_actions: ['show']
            list:
                title: 'Поколения'
                fields:
                    - { property: 'carModel.displayName', label: 'Модель' }
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'carModel', label: 'Модель', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Название' }
            edit:
                fields:
                    - { property: 'carModel', type_options: { disabled: true } }

        Modification:
            class: AppBundle\Entity\CarModification
            controller: AppBundle\Controller\Admin\CarModificationController
            disabled_actions: ['show']
            list:
                title: 'Справочник Автомобилей'
                fields:
                    - { property: 'carGeneration.displayName', label: 'Поколение' }
                    - { property: 'name', label: 'Название' }
                    - { property: 'case.name', label: 'Кузов' }
                    - { property: 'engine', label: 'Двигатель' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'transmission.name', label: 'Трансмиссия' }
                    - { property: 'wheelDrive.name', label: 'Привод' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С', type: 'string' }
                    - { property: 'till', label: 'По', type: 'string' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }
            form:
                fields:
                    - { property: 'carGeneration', label: 'Поколение', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Название' }
                    - { property: 'case', type: AppBundle\Form\Type\CarcaseType, label: 'Кузов' }
                    - { property: 'engine', label: 'Двигатель' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'transmission', type: AppBundle\Form\Type\CarTransmissionType, label: 'Трасмиссия' }
                    - { property: 'wheelDrive', type: AppBundle\Form\Type\CarWheelDriveType, label: 'Привод' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'Начало производства' }
                    - { property: 'till', label: 'Конец производства' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }
            new:
                fields: ['-name']
            edit:
                fields:
                    - { property: 'name', type_options: { disabled: true } }
