easy_admin:
    entities:
        OpenOrders:
            class: AppBundle\Entity\Order
            label: 'Заказы'
            list:
                title: 'Открытые Заказы'
                dql_filter: 'entity.closeddate IS NULL'
                fields:
                    - { property: 'id', label: 'Номер' }
                    - { property: 'status', label: 'Статус' }
                    - { property: 'startdate', label: 'Дата начала' }
                    - { property: 'car.displayName', label: 'Автомобиль' }
                    - { property: 'car.carmodification.name', label: 'Модификация' }
                    - { property: 'client.person.fullName', label: 'Клиент' }
                    - { property: 'readableCosts', label: 'Работы/Запчасти' }
                    - { property: 'client.person.fullName', label: 'Последний комментарий' }
        ClosedOrders:
            class: AppBundle\Entity\Order
            label: 'Заказы'
            list:
                title: 'Закрытые Заказы'
                dql_filter: 'entity.closeddate IS NOT NULL'
                fields:
                    - { property: 'id', label: 'Номер' }
                    - { property: 'status', label: 'Статус' }
                    - { property: 'startdate', label: 'Дата начала' }
                    - { property: 'closeddate', label: 'Дата закрытия' }
                    - { property: 'car.displayName', label: 'Автомобиль' }
                    - { property: 'car.carmodification.name', label: 'Модификация' }
                    - { property: 'client.person.fullName', label: 'Клиент' }
                    - { property: 'readableCosts', label: 'Работы/Запчасти' }
                    - { property: 'client.person.fullName', label: 'Последний комментарий' }
        Orders:
            class: AppBundle\Entity\Order
            label: 'Заказы'
            list:
                title: 'Все Заказы'
                fields:
                    - { property: 'id', label: 'Номер' }
                    - { property: 'status', label: 'Статус' }
                    - { property: 'startdate', label: 'Дата начала' }
                    - { property: 'closeddate', label: 'Дата закрытия' }
                    - { property: 'car.displayName', label: 'Автомобиль' }
                    - { property: 'car.carmodification.name', label: 'Модификация' }
                    - { property: 'client.person.fullName', label: 'Клиент' }
                    - { property: 'readableCosts', label: 'Работы/Запчасти' }
                    - { property: 'client.person.fullName', label: 'Последний комментарий' }
        Jobs:
            class: AppBundle\Entity\Jobadvice


        Client:
            class: AppBundle\Entity\Client
        Person:
            class: AppBundle\Entity\Person
        Car:
            class: AppBundle\Entity\Car
            label: 'Автомобили'
            list:
                title: 'Автомобили'
                fields:
                    - { property: 'client.person.fullName', label: 'Владелец' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'carmake.name', label: 'Производитель' }
                    - { property: 'carmodel.name', label: 'Модель' }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false }


        Part:
            class: AppBundle\Entity\Part
            label: 'Запчасти'
        Motion:
            class: AppBundle\Entity\Motion
        Manufacturer:
            class: AppBundle\Entity\Manufacturer
            disabled_actions: ['show']
            label: 'Производитель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }

        Carmake:
            class: AppBundle\Entity\Carmake
            disabled_actions: ['show']
            label: 'Производитель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
        Model:
            class: AppBundle\Entity\Carmodel
            disabled_actions: ['show']
            label: 'Модель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
        Generation:
            class: AppBundle\Entity\Cargeneration
            disabled_actions: ['show']
            list:
                title: 'Поколения'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'carmodel.name', label: 'Модель' }
                    - { property: 'carmodel.carmake.name', label: 'Производитель' }
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
        Modification:
            class: AppBundle\Entity\Carmodification
            disabled_actions: ['show']
            list:
                title: 'Модификации'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'cargeneration.name', label: 'Поколение' }
                    - { property: 'cargeneration.carmodel.carmake.name', label: 'Производитель' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С' }
                    - { property: 'till', label: 'По' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'cargeneration', label: 'Поколение' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С' }
                    - { property: 'till', label: 'По' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }


        Item:
            class: AppBundle\Entity\Item
