easy_admin:
    entities:
        Order:
            class: AppBundle\Entity\Order
            controller: AppBundle\Controller\Admin\OrderController
            templates:
                list: 'easy_admin/order/list.html.twig'
                new: 'easy_admin/order/new.html.twig'
            label: 'Заказ'
            list:
                title: 'Заказы'
                fields:
                    - { property: 'id', label: 'Номер', template: 'easy_admin/order/field_id.html.twig' }
                    - { property: 'status.readableName', label: 'Статус' }
                    - { property: 'startedAt', label: 'Дата начала', type: 'datetime' }
                    - { property: 'car', label: 'Автомобиль', template: 'easy_admin/order/field_car.html.twig' }
                    - { property: 'car.gosnomer', label: 'Госномер', template: 'easy_admin/car/field_gosnomer_img.html.twig' }
                    - { property: 'client', label: 'Клиент' }
                    - { property: 'readableCosts', label: 'Работы/Запчасти' }
            form:
                fields:
                    - { property: 'client', label: 'Клиент', type: 'easyadmin_autocomplete' }
                    - { property: 'car', label: 'Автомобиль', type: 'easyadmin_autocomplete' }
                    - { property: 'parts', label: 'Запчасти', type: 'easyadmin_autocomplete' }
                    - { property: 'jobs', label: 'Работы', type: 'easyadmin_autocomplete' }
                    - { property: 'description', label: 'Описание' }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'status.readableName' }
                    - { property: 'startedAt', type: 'datetime' }
                    - { property: 'car' }
                    - { property: 'mileage' }
                    - { property: 'client' }
                    - { property: 'readableCosts' }
                    - { property: 'description' }
                    - { property: 'notes' }
            new:
                title: 'Создать заказ'
        Jobs:
            class: AppBundle\Entity\JobAdvice
        Partitem:
            class: AppBundle\Entity\PartItem
        Jobitem:
            class: AppBundle\Entity\JobItem

        Client:
            class: AppBundle\Entity\Client
            controller: AppBundle\Controller\Admin\ClientController
            list:
                title: 'Пользователи'
                fields:
                    - { property: 'person', label: 'Клиент', template: 'easy_admin/client/field_person.html.twig' }
                    - { property: 'person.telephone', label: 'Телефон', type: 'tel' }
                    - { property: 'person.email', label: 'Email', type: 'email' }
                    - { property: 'wallet', label: 'Баланс' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'employee', label: 'Сотрудник?', type: 'boolean' }
            form:
                fields:
                    - { property: 'person', label: 'Клиент' }
                    - { property: 'wallet', label: 'Баланс' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'employee', label: 'Сотрудник?' }
        Person:
            class: AppBundle\Entity\Person
            search:
                fields: ['firstname', 'lastname']
            list:
                fields:
                    - { property: 'fullName', label: 'Ф.И.О' }
                    - { property: 'telephone', label: 'Телефон', type: 'tel' }
            form:
                fields:
                    - { property: 'firstname', label: 'Имя' }
                    - { property: 'lastname', label: 'Фамилия' }
                    - { property: 'telephone', label: 'Телефон' }

        Car:
            class: AppBundle\Entity\Car
            label: 'Автомобили'
            search:
                fields: ['gosnomer', 'vin']
            list:
                title: 'Автомобили'
                fields:
                    - { property: 'client', label: 'Владелец' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'carModel.displayName', label: 'Модель' }
                    - { property: 'carModification.name', label: 'Комплектация' }
                    - { property: 'mileage', label: 'Пробег' }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false, template: 'easy_admin/car/field_gosnomer_img.html.twig' }
            show:
                fields:
                    - { property: 'client', label: 'Владелец' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'carModel.displayName', label: 'Модель' }
                    - { property: 'carModification.name', label: 'Комплектация' }
                    - { property: 'mileage', label: 'Пробег' }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false }
            form:
                fields:
                    - { property: 'description', label: 'Описание', sortable: false }
                    - { property: 'carModification', label: 'Модель', type: 'easyadmin_autocomplete' }
            new:
                fields:
                    - { property: 'client', label: 'Владелец', type: 'easyadmin_autocomplete' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false }

        Part:
            class: AppBundle\Entity\Part
            label: 'Запчасти'
            list:
                fields:
                    - { property: 'manufacturer.name', label: 'Производитель' }
                    - { property: 'partname', label: 'Название' }
                    - { property: 'partnumber', label: 'Номер' }
                    - { property: 'price', label: 'Цена' }
            form:
                fields:
                    - { property: 'manufacturer', label: 'Производитель' }
                    - { property: 'partname', label: 'Название' }
                    - { property: 'partnumber', label: 'Номер' }
                    - { property: 'price', label: 'Цена' }
            edit:
                fields: ['-price']
        Motion:
            class: AppBundle\Entity\Motion
            disabled_actions: ['show', 'edit', 'new', 'search']
        Manufacturer:
            class: AppBundle\Entity\Manufacturer
            disabled_actions: ['show']
            label: 'Производитель'
            search:
                fields: ['name']
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }

        Model:
            class: AppBundle\Entity\CarModel
            disabled_actions: ['show']
            label: 'Модель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'manufacturer', label: 'Производитель', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Название' }
        Generation:
            class: AppBundle\Entity\CarGeneration
            disabled_actions: ['show']
            list:
                title: 'Поколения'
                fields:
                    - { property: 'carModel', label: 'Модель' }
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'carModel', label: 'Модель', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Название' }
        Modification:
            class: AppBundle\Entity\CarModification
            controller: AppBundle\Controller\Admin\CarModelController
            disabled_actions: ['show']
            list:
                title: 'Справочник Автомобилей'
                fields:
                    - { property: 'carGeneration', label: 'Поколение' }
                    - { property: 'name', label: 'Название' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С', type: 'string' }
                    - { property: 'till', label: 'По', type: 'string' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }
            form:
                fields:
                    - { property: 'carGeneration', label: 'Поколение', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Название' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С' }
                    - { property: 'till', label: 'По' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }
