easy_admin:
    entities:
        Order:
            class: AppBundle\Entity\Order
            label: 'Заказ'
            list:
                title: 'Заказы'
                fields:
                    - { property: 'id', label: 'Номер' }
                    - { property: 'status', label: 'Статус' }
                    - { property: 'startedAt', label: 'Дата начала', type: 'datetime' }
                    - { property: 'car', label: 'Автомобиль' }
                    - { property: 'client', label: 'Клиент' }
                    - { property: 'readableCosts', label: 'Работы/Запчасти' }
            form:
                fields:
                    - { property: 'car', label: 'Автомобиль', type: 'easyadmin_autocomplete' }
                    - { property: 'parts', label: 'Запчасти', type: 'easyadmin_autocomplete' }
                    - { property: 'jobs', label: 'Работы', type: 'easyadmin_autocomplete' }
                    - { property: 'description', label: 'Описание' }
            new:
                title: 'Создать заказ'
        Jobs:
            class: AppBundle\Entity\Jobadvice
        Partitem:
            class: AppBundle\Entity\Partitem
        Jobitem:
            class: AppBundle\Entity\Jobitem

        Client:
            class: AppBundle\Entity\Client
            search:
                fields: ['person', 'description']
            list:
                title: 'Пользователи'
                fields:
                    - { property: 'person', label: 'Клиент' }
                    - { property: 'wallet', label: 'Баланс' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'employee', label: 'Сотрудник?' }
            form:
                fields:
                    - { property: 'person', label: 'Клиент' }
                    - { property: 'wallet', label: 'Баланс' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'employee', label: 'Сотрудник?' }
        Person:
            class: AppBundle\Entity\Person
            search:
                fields: ['firstname', 'lastname', 'mobilephone']
            list:
                fields:
                    - { property: 'fullName', label: 'Ф.И.О' }
                    - { property: 'mobilephone', label: 'Телефон' }
            form:
                fields:
                    - { property: 'firstname', label: 'Имя' }
                    - { property: 'lastname', label: 'Фамилия' }
                    - { property: 'mobilephone', label: 'Телефон' }

        Car:
            class: AppBundle\Entity\Car
            label: 'Автомобили'
            search:
                fields: ['gosnomer', 'vin']
            list:
                title: 'Автомобили'
                fields:
                    - { property: 'client', label: 'Владелец' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'carmake', label: 'Производитель' }
                    - { property: 'carmodel', label: 'Модель' }
                    - { property: 'mileage', label: 'Пробег' }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false }
            form:
                fields:
                    - { property: 'client', label: 'Владелец' }
                    - { property: 'vin', label: 'VIN', sortable: false }
                    - { property: 'carmake', label: 'Производитель' }
                    - { property: 'carmodel', label: 'Модель' }
                    - { property: 'gosnomer', label: 'Гос. Номер', sortable: false }
                    - { property: 'description', label: 'Описание', sortable: false }


        Part:
            class: AppBundle\Entity\Part
            label: 'Запчасти'
            list:
                fields:
                    - { property: 'manufacturer.name', label: 'Производитель' }
                    - { property: 'partname', label: 'Название' }
                    - { property: 'partnumber', label: 'Номер' }
                    - { property: 'price', label: 'Цена' }
            form:
                fields:
                    - { property: 'manufacturer', label: 'Производитель' }
                    - { property: 'partname', label: 'Название' }
                    - { property: 'partnumber', label: 'Номер' }
                    - { property: 'price', label: 'Цена' }
            edit:
                fields: ['-price']
        Motion:
            class: AppBundle\Entity\Motion
            disabled_actions: ['show', 'edit', 'new', 'search']
        Manufacturer:
            class: AppBundle\Entity\Manufacturer
            disabled_actions: ['show']
            label: 'Производитель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }

        Carmake:
            class: AppBundle\Entity\Carmake
            disabled_actions: ['show']
            label: 'Производитель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
        Model:
            class: AppBundle\Entity\Carmodel
            disabled_actions: ['show']
            label: 'Модель'
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
        Generation:
            class: AppBundle\Entity\Cargeneration
            disabled_actions: ['show']
            list:
                title: 'Поколения'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'carmodel.name', label: 'Модель' }
                    - { property: 'carmodel.carmake.name', label: 'Производитель' }
            list:
                title: 'Производители'
                fields:
                    - { property: 'name', label: 'Название' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
        Modification:
            class: AppBundle\Entity\Carmodification
            disabled_actions: ['show']
            list:
                title: 'Модификации'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'cargeneration.name', label: 'Поколение' }
                    - { property: 'cargeneration.carmodel.carmake.name', label: 'Производитель' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С', type: 'string' }
                    - { property: 'till', label: 'По', type: 'string' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }
            form:
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'cargeneration', label: 'Поколение' }
                    - { property: 'hp', label: 'л.с.' }
                    - { property: 'doors', label: 'Дверей' }
                    - { property: 'from', label: 'С' }
                    - { property: 'till', label: 'По' }
                    - { property: 'maxspeed', label: 'Макс. скорость' }
                    - { property: 's0to100', label: 'Разгон' }
                    - { property: 'tank', label: 'Объём бака' }


        Item:
            class: AppBundle\Entity\Item
