easy_admin:
    entities:
      Car:
        class: AppBundle\Entity\Car
        label: 'Автомобили'
        list:
          title: 'Автомобили'
          fields:
            - { property: 'client.person.fullName', label: 'Владелец' }
            - { property: 'vin', label: 'VIN', sortable: false }
            - { property: 'carmake.name', label: 'Производитель' }
            - { property: 'carmodel.name', label: 'Модель' }
            - { property: 'gosnomer', label: 'Гос. Номер', sortable: false }
      Generation:
        class: AppBundle\Entity\Cargeneration
        list:
          title: 'Поколения'
      Carmake:
        class: AppBundle\Entity\Carmake
        label: 'Производитель'
      Model:
        class: AppBundle\Entity\Carmodel
        label: 'Модель'
      Modification:
        class: AppBundle\Entity\Carmodification
        list:
          title: 'Модификации'
        show:
          title: 'Модификация'
      Part:
        class: AppBundle\Entity\Part
        label: 'Запчасти'
      Item:
        class: AppBundle\Entity\Item
      Client:
        class: AppBundle\Entity\Client
      Person:
        class: AppBundle\Entity\Person
      Part:
        class: AppBundle\Entity\Part
      Motion:
        class: AppBundle\Entity\Motion
      Manufacturer:
        class: AppBundle\Entity\Manufacturer
      Jobs:
        class: AppBundle\Entity\Jobadvice
