easy_admin:
    design:
        menu:
            - { entity: 'Order', label: 'Заказы', icon: 'list' }
            - { label: 'Списки' }
            - { entity: 'Person', label: 'Люди', icon: 'users' }
            - { entity: 'Organization', label: 'Организации', icon: 'industry' }
            - { entity: 'Car', label: 'Автомобили', icon: 'car' }
            - { entity: 'Employee', label: 'Сотрудники', icon: 'users' }
            - { label: 'Склад' }
            - { entity: 'Part', label: 'Запчасти', icon: 'cogs' }
            - { entity: 'Service', label: 'Работы', icon: 'wrench' }
            - { entity: 'Motion', label: 'Движения', icon: 'truck' }
            - { label: 'Справочники' }
            - { entity: 'Manufacturer', label: 'Производитель', icon: 'industry' }
            - { entity: 'Model', label: 'Модель', icon: 'car' }
            - { entity: 'Generation', label: 'Поколение', icon: 'car' }
            - { entity: 'Modification', label: 'Модификация', icon: 'car' }
