easy_admin:
    design:
        menu:
            - { label: 'Заказы' }
            - { entity: 'Order', label: 'Заказы', icon: 'list' }
            - { label: 'Клиенты' }
            - { entity: 'Client', label: 'Пользователи', icon: 'users' }
            - { entity: 'Person', label: 'Люди', icon: 'users' }
            - { entity: 'Car', label: 'Автомобили', icon: 'car' }
            - { label: 'Склад' }
            - { entity: 'Part', label: 'Запчасти', icon: 'cogs' }
            - { entity: 'Motion', label: 'Движения', icon: 'truck' }
            - { label: 'Справочники' }
            - { entity: 'Manufacturer', label: 'Производители', icon: 'industry' }
            - { entity: 'Model', label: 'Модели' }
            - { entity: 'Generation', label: 'Поколения' }
            - { entity: 'Modification', label: 'Модификации' }
