framework:
    router:
        strict_requirements: true
    session:
        handler_id:  session.handler.native_file
        save_path:   "/tmp/sessions/%kernel.environment%"
    profiler: { only_exceptions: false }
