services:
    _defaults:
        public: false
        autowire: by_id

    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: [ kernel.event_subscriber ]

        Symfony\Component\Form\AbstractType:
            tags: [ form.type ]

        Twig_Extension:
            tags: [ twig.extension ]

    App\:
        resource: ../src/{EventListener,Form/Type,Twig/Extension, Part}

    App\Controller\:
        resource: ../src/Controller
        public: true

    Symfony\Component\PropertyAccess\PropertyAccessor:
        alias: property_accessor
    Doctrine\ORM\EntityManager:
        alias: doctrine.orm.default_entity_manager

    App\Part\Finder:
        arguments:
            - '@csa_guzzle.client.ixora_ws'
