_easy_admin:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    type: annotation
    condition: "request.getHost() matches '/%admin_host_pattern%/'"

_admin:
    resource: './routes/admin.yaml'
    condition: "request.getHost() matches '/%admin_host_pattern%/'"
    name_prefix: admin_

_www:
    resource: './routes/www.yaml'
    condition: "request.getHost() matches '/%www_host_pattern%/'"
    name_prefix: www_

_default:
    resource: '../src/Controller/DefaultController.php'
    type: annotation
