parameters:
    locale: ru
    env(APP_VERSION): null

services:
    _defaults:
        public: false
        autowire: by_id
        autoconfigure: true

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: { name: doctrine.event_subscriber }

        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags: { name: controller.argument_value_resolver }

    App\:
        resource: '../src'
        exclude: '../src/{Entity,Model}'
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    App\Part\Finder:
        arguments:
            - '@csa_guzzle.client.ixora_ws'

    App\Partner\Ixora\Orders:
        arguments:
            - '@csa_guzzle.client.ixora_ws'
            - '@serializer'
